:wrench: First attempt at cloud-init snap installation

diff --git a/deployment/dsvm_images/cloud_init/cloud-init-buildimage-ubuntu-2004.yaml b/deployment/dsvm_images/cloud_init/cloud-init-buildimage-ubuntu-2004.yaml
--- a/deployment/dsvm_images/cloud_init/cloud-init-buildimage-ubuntu-2004.yaml
+++ b/deployment/dsvm_images/cloud_init/cloud-init-buildimage-ubuntu-2004.yaml
@@ -20,11 +20,6 @@ apt:
       source: "deb https://packagecloud.io/AtomEditor/atom/any/ any main"
       keyid: 0A0FAB860D48560332EFB581B75442BBDE9E3B09  # https://packagecloud.io/AtomEditor/atom (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>
 
-    # Official DBeaver PPA (from https://dbeaver.io/download/)
-    dbeaver.list:
-      source: "deb http://ppa.launchpad.net/serge-rider/dbeaver-ce/ubuntu focal main"
-      keyid: 30ECE32520D438C21E16BF884A71B51882788FD2  # Launchpad PPA for Serge Rider
-
     microsoft-general.list:
       source: "deb https://packages.microsoft.com/ubuntu/20.04/prod focal main"
       keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF  # Microsoft (Release signing) <gpgsecurity@microsoft.com>
@@ -60,10 +55,6 @@ apt:
     sbt.list:
       source: "deb https://repo.scala-sbt.org/scalasbt/debian all main"
       keyid: 2EE0EA64E40A89B84B2DF73499E82A75642AC823  # sbt build tool <scalasbt@gmail.com>
-
-    vscode.list:
-      source: "deb https://packages.microsoft.com/repos/vscode stable main"
-      keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF  # Microsoft (Release signing) <gpgsecurity@microsoft.com>
 
 
 write_files:
@@ -171,6 +162,10 @@ write_files:
 packages:
   - {{packages-apt.list}}
 
+# Packages to install with snap
+snap:
+  commands:
+    - snap install {{packages-snap.list}}
 
 # Set the NTP server
 # By default we use Google's NTP servers which are incompatible with other servers due to leap-second smearing
@@ -181,7 +176,6 @@ ntp:
     {{#shm.time.ntp.serverAddresses}}
     - {{.}}
     {{/shm.time.ntp.serverAddresses}}
-
 
 # List of commands to run using `/bin/sh`
 # When changing these lines try to ensure that everything is checked as close as possible to the point when it is installed/configured.
@@ -199,23 +193,21 @@ runcmd:
   # Suppress apt prompts and warning messages
   - echo "Suppressing apt prompts..."
   - export DEBIAN_FRONTEND=noninteractive
+  # Add snap to path
+  - echo "Adding snap to path..."
+  - PATH=$PATH:/snap/bin
 
-  - echo ">=== $(date +%s) Installing additional deb/snap/source packages ===<"
-  # NVidia setup (necessary packages from https://www.tensorflow.org/install/gpu are in our apt install list)
-  - echo "Checking NVidia requirements for tensorflow..."
-  - if [ "$(which nvidia-smi)" = "" ]; then echo "Could not install NVidia tools!"; exit 1; else echo "... successfully installed NVidia requirements"; fi
+  - echo ">=== $(date +%s) Installing additional deb/source packages ===<"
   # Microsoft ODBC tools
   - echo "Installing Microsoft ODBC tools..."
   - ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools
   - PATH=$PATH:/opt/mssql-tools/bin
+  - echo "export DOTNET_CLI_TELEMETRY_OPTOUT=1" >> /etc/bash.bashrc
   - if [ "$(which sqlcmd)" = "" ]; then echo "Could not install Microsoft ODBC tools!"; exit 1; else echo "... successfully installed Microsoft ODBC tools"; fi
   # Azure Data Studio
   - echo "Installing Azure Data Studio..."
   - /opt/build/download_and_install_deb.sh azuredatastudio
   - if [ "$(which azuredatastudio)" = "" ]; then echo "Could not install Azure Data Studio!"; exit 1; else echo "... successfully installed Azure Data Studio"; fi
-  # DBeaver and drivers
-  - echo "Installing DBeaver..."
-  - if [ "$(which dbeaver)" = "" ]; then echo "Could not install DBeaver!"; exit 1; else echo "... successfully installed DBeaver"; fi
   # Install drivers from maven
   - echo "Installing DBeaver drivers..."
   - DBEAVER_DRIVER_DIR="/usr/share/dbeaver/drivers/maven/maven-central"
@@ -239,11 +231,6 @@ runcmd:
   - echo "-Djava.security.auth.login.config=/etc/jaas.conf" >> /usr/share/dbeaver/dbeaver.ini
   - ls -alh ${DBEAVER_DRIVER_DIR}/*
   - echo "... successfully installed DBeaver drivers";
-  # Install PyCharm
-  - echo "Installing PyCharm..."
-  - snap install pycharm-community --classic
-  - PATH=$PATH:/snap/bin
-  - if [ "$(which pycharm-community)" = "" ]; then echo "Could not install PyCharm!"; exit 1; else echo "... successfully installed PyCharm"; fi
   # Install RStudio,
   - echo "Installing RStudio..."
   - /opt/build/download_and_install_deb.sh rstudio
@@ -310,8 +297,6 @@ runcmd:
   - export JULIA_COPY_STACKS=1
   - export PYTHON="$(which python3)"  # link Julia against system Python 3
   - julia -e "using Pkg; Pkg.add($JULIA_PACKAGES); for package in $JULIA_PACKAGES; Pkg.build(package); end"
-  # Move the locally-installed Julia kernel to the main directory
-  - mv /root/.local/share/jupyter ${JULIA_BASE_DIR}/share || exit 1
   # Ensure that Julia depot is globally readable
   - chmod -R o=u,o-w ${JULIA_BASE_DIR}/depot/
   # Write Julia environment variables to global .bashrc
@@ -322,7 +307,8 @@ runcmd:
   - MISSING_JULIA_PACKAGES=$(julia -e "for package in $JULIA_PACKAGES; try; abspath(joinpath(dirname(Base.find_package(package)))); @eval using \$(Symbol(package)); catch e; println(package); end; end;")
   - if [ "$MISSING_JULIA_PACKAGES" ]; then echo "Could not install Julia packages - $MISSING_JULIA_PACKAGES"; exit 1; else echo "... successfully installed Julia"; fi
   # Add the Julia kernel to Jupyter
-  - jupyter kernelspec install ${JULIA_BASE_DIR}/share/jupyter/kernels/julia-* || echo "Could not install Julia kernel!" && exit 1
+  - mv /root/.local/share/jupyter ${JULIA_BASE_DIR}/share
+  - jupyter kernelspec install ${JULIA_BASE_DIR}/share/jupyter/kernels/julia-* || (echo "Could not install Julia kernel!" && exit 1)
 
   # Install python versions
   - export PYTHON_VERSIONS="$(ls /opt/build/python-requirements-py*txt | rev | cut -d '-' -f 1 | rev | sed 's/py//; s/\.txt//')"
@@ -332,7 +318,7 @@ runcmd:
       sed 's/<.*//; s/=.*//; s/>.*//' /opt/build/python-requirements-py${python_version}.txt > /opt/build/packages/packages-python-pypi-${python_version}.list
       chmod 0444 /opt/build/packages/packages-python-pypi-${python_version}.list
       # Install python versions
-      /opt/build/install_python_version.sh py${python_version} || exit 1
+      /opt/build/install_python_version.sh py${python_version} || (echo "Failed to install Python ${python_version}" && exit 1)
     done
   - echo "Installed python versions"
   - du --si -d 1 /opt/pyenv/versions
@@ -359,7 +345,7 @@ runcmd:
   # Add the new Python kernels to Jupyter
   - |
     for python_version in $PYTHON_VERSIONS; do
-      jupyter kernelspec install /opt/pyenv/versions/*/share/jupyter/kernels/py${python_version} || echo "Could not install Python $python_version kernel!" && exit 1
+      jupyter kernelspec install /opt/pyenv/versions/*/share/jupyter/kernels/py${python_version} || (echo "Could not install Python $python_version kernel!" && exit 1)
     done
 
   # Install any missing R packages - approximately 40 minutes
@@ -383,7 +369,7 @@ runcmd:
   - ln -s /usr/local/lib/R/site-library/IRkernel/kernelspec /usr/local/lib/R/site-library/IRkernel/R${R_VERSION}
   - |
     sed -i "s|\"display_name\":.*\R.*|\"display_name\": \"R ${R_VERSION}\",|" /usr/local/lib/R/site-library/IRkernel/kernelspec/kernel.json
-  - jupyter kernelspec install /usr/local/lib/R/site-library/IRkernel/R${R_VERSION} || echo "Could not install R kernel!" &&exit 1
+  - jupyter kernelspec install /usr/local/lib/R/site-library/IRkernel/R${R_VERSION} || (echo "Could not install R kernel!" && exit 1)
 
   # Check for successful installations
   - echo ">=== $(date +%s) Checking environment configuration ===<"
@@ -413,8 +399,8 @@ runcmd:
   - apt-get autoremove -y --purge
   - apt-get clean
   # Remove temporary files
-  - find /root/ -mindepth 1 -delete  # remove all files from root's home directory
   - tmpreaper 10m /tmp/ /var/tmp/    # remove temporary files that have not been accessed in 10 minutes
+  - find /root/ -mindepth 1 -delete  # remove all files from root's home directory including dotfiles
   # Log space saved
   - USED_BYTES_NEW=$(df / | tail -n 1 | awk '{printf $3}')
   - echo "Successfully reclaimed $(numfmt --to=iec-i --suffix=B $(($USED_BYTES_OLD - $USED_BYTES_NEW))) of disk space"
