:sparkles: Switch to using a YAML file for specifying Python packages

diff --git a/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml b/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml
--- a/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml
+++ b/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml
@@ -85,14 +85,18 @@ write_files:
     permissions: "0500"
     content: |
       {{download_and_install_deb.sh}}
-  - path: "/opt/build/install_python_version.sh"
+  - path: "/opt/build/install_python_versions.py"
     permissions: "0500"
     content: |
-      {{install_python_version.sh}}
+      {{install_python_versions.py}}
   - path: "/opt/build/packages/packages-julia.list"
     permissions: "0444"
     content: |
       {{packages-julia.list}}
+  - path: "/opt/build/packages-python.yaml"
+    permissions: "0444"
+    content: |
+      {{packages-python.yaml}}
   - path: "/opt/build/packages/packages-r-bioconductor.list"
     permissions: "0444"
     content: |
@@ -101,18 +105,6 @@ write_files:
     permissions: "0444"
     content: |
       {{packages-r-cran.list}}
-  - path: "/opt/build/python-requirements-py38.txt"
-    permissions: "0444"
-    content: |
-      {{python-requirements-py38.txt}}
-  - path: "/opt/build/python-requirements-py39.txt"
-    permissions: "0444"
-    content: |
-      {{python-requirements-py39.txt}}
-  - path: "/opt/build/python-requirements-py310.txt"
-    permissions: "0444"
-    content: |
-      {{python-requirements-py310.txt}}
   - path: "/opt/build/python-pyproject-template.toml"
     permissions: "0400"
     content: |
@@ -248,6 +240,7 @@ runcmd:
   - rm -rf $PYENV_ROOT 2> /dev/null
   - PATH="$PYENV_ROOT/bin:$PATH"  # NB. pyenv needs to be at the beginning of the path so that it can override other python versions
   - curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
+  - pyenv doctor
   - if [ "$(which pyenv)" = "" ]; then echo "Could not install pyenv!"; exit 1; else echo "... successfully installed pyenv"; fi
   # Install VSCode extensions
   - echo ">=== Install VSCode extensions... ===<"
@@ -313,16 +306,8 @@ runcmd:
   - jupyter kernelspec install ${JULIA_BASE_DIR}/share/jupyter/kernels/julia-* || (echo "Could not install Julia kernel!" && exit 1)
 
   # Install python versions
-  - export PYTHON_VERSIONS="$(ls /opt/build/python-requirements-py*txt | rev | cut -d '-' -f 1 | rev | sed 's/py//; s/\.txt//' | sort -n)"
-  - |
-    for python_version in $PYTHON_VERSIONS; do
-      # Create simple list of required packages for checking installation
-      sed 's/<.*//; s/=.*//; s/>.*//' /opt/build/python-requirements-py${python_version}.txt > /opt/build/packages/packages-python-pypi-${python_version}.list
-      chmod 0444 /opt/build/packages/packages-python-pypi-${python_version}.list
-      # Install python versions
-      /opt/build/install_python_version.sh $PYENV_ROOT py${python_version} || (echo "Failed to install Python ${python_version}" && exit 1)
-    done
-  - echo "Installed python versions"
+  - /opt/build/install_python_versions.py /opt/build/packages-python.yaml
+  - echo "Installed python versions:"
   - du --si -d 1 ${PYENV_ROOT}/versions
   # Configure pyenv: use a local PYENV_ROOT with the global versions symlinked into it
   - export PYENV_LOCAL_ROOT='${HOME}/.pyenv'
@@ -344,8 +329,8 @@ runcmd:
     done
   # Add the new Python kernels to Jupyter
   - |
-    for python_version in $PYTHON_VERSIONS; do
-      jupyter kernelspec install ${PYENV_ROOT}/versions/*/share/jupyter/kernels/py${python_version} || (echo "Could not install Python $python_version kernel!" && exit 1)
+    for python_version in $(ls ${PYENV_ROOT}/versions); do
+      jupyter kernelspec install ${PYENV_ROOT}/versions/${python_version}/share/jupyter/kernels/python* || (echo "Could not install Python ${python_version} kernel!" && exit 1)
     done
 
   # Install any missing R packages - approximately 1 hr
