:bug: Fix build script exit syntax

diff --git a/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml b/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml
--- a/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml
+++ b/deployment/secure_research_desktop/cloud_init/cloud-init-buildimage-ubuntu-1804.mustache.yaml
@@ -173,6 +173,12 @@ ntp:
 # If any of the installation/configuration checks fail then end the cloud-init process immediately by calling `exit 1`.
 # This allows us to (i) not waste time completing a build once a step has failed and (ii) easily tell when and why a build failed using the analyse_build.py script.
 runcmd:
+  - |
+    # Utility function to send a message to stderr then return an error code
+    die() {
+      echo "$1" >&2
+      exit "${2-1}"
+    }
   - sleep 10  # ensure that run commands are cleanly time-separated from other cloud-init commands
   - echo ">=== $(date +%s) Preparing system for installation ===<"
   # Install python packages used in the rest of the build
@@ -247,7 +253,7 @@ runcmd:
   - rm -rf $PYENV_ROOT 2> /dev/null
   - PATH="$PYENV_ROOT/bin:$PATH"  # NB. pyenv needs to be at the beginning of the path so that it can override other python versions
   - curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
-  - pyenv doctor || (echo "Could not configure pyenv!" && exit 1)
+  - pyenv doctor || die "Could not configure pyenv!"
   - if [ "$(which pyenv)" = "" ]; then echo "Could not install pyenv!"; exit 1; else echo "... successfully installed pyenv"; fi
   # Install VSCode extensions
   - echo "Install VSCode extensions..."
@@ -255,10 +261,10 @@ runcmd:
   # Get icons for webapps
   - echo "Downloading icons..."
   - mkdir -p /opt/icons
-  - wget https://raw.githubusercontent.com/sagemathinc/cocalc/master/src/packages/assets/cocalc-icon.svg -O /tmp/cocalc-icon.svg || (echo "Could not find CoCalc icon!" && exit 1)
-  - convert -density 983 -transparent white /tmp/cocalc-icon.svg /opt/icons/cocalc.png || (echo "Could not convert CoCalc icon!" && exit 1) # this should give a 1024x1024 png
-  - wget https://raw.githubusercontent.com/hackmdio/codimd/develop/public/favicon.png -O /opt/icons/codimd.png || (echo "Could not find CodiMD icon!" && exit 1)
-  - wget https://about.gitlab.com/images/press/logo/png/gitlab-icon-rgb.png -O /opt/icons/gitlab.png || (echo "Could not find GitLab icon!" && exit 1)
+  - wget https://raw.githubusercontent.com/sagemathinc/cocalc/master/src/packages/assets/cocalc-icon.svg -O /tmp/cocalc-icon.svg || die "Could not find CoCalc icon!"
+  - convert -density 983 -transparent white /tmp/cocalc-icon.svg /opt/icons/cocalc.png || die "Could not convert CoCalc icon!" # this should give a 1024x1024 png
+  - wget https://raw.githubusercontent.com/hackmdio/codimd/develop/public/favicon.png -O /opt/icons/codimd.png || die "Could not find CodiMD icon!"
+  - wget https://about.gitlab.com/images/press/logo/png/gitlab-icon-rgb.png -O /opt/icons/gitlab.png || die "Could not find GitLab icon!"
 
   # Manually update ClamAV signature database
   - echo ">=== $(date +%s) Updating ClamAV database ===<"
@@ -310,13 +316,13 @@ runcmd:
   - if [ "$MISSING_JULIA_PACKAGES" ]; then echo "Could not install Julia packages - $MISSING_JULIA_PACKAGES"; exit 1; else echo "... successfully installed Julia"; fi
   # Add the Julia kernel to Jupyter
   - mv /root/.local/share/jupyter ${JULIA_BASE_DIR}/share
-  - jupyter kernelspec install ${JULIA_BASE_DIR}/share/jupyter/kernels/julia-* || (echo "Could not install Julia kernel!" && exit 1)
+  - jupyter kernelspec install ${JULIA_BASE_DIR}/share/jupyter/kernels/julia-* || die "Could not install Julia kernel!"
 
   # Install python versions
   - /opt/build/pyenv/build_requirements.py /opt/build/pyenv/packages-python.yaml
   - |
     for PYTHON_VERSION in $(ls /opt/build/python-*-requirements.txt | cut -d '-' -f 2 | sort -V); do
-      /opt/build/pyenv/install.sh $PYTHON_VERSION || (echo "Could not install Python ${PYTHON_VERSION}!" && exit 1)
+      /opt/build/pyenv/install.sh $PYTHON_VERSION || die "Could not install Python ${PYTHON_VERSION}!";
     done
 
   # Configure pyenv: use a local PYENV_ROOT with the global versions symlinked into it
@@ -342,8 +348,8 @@ runcmd:
     done
   # Add the new Python kernels to Jupyter
   - |
-    for python_version in $(ls ${PYENV_ROOT}/versions); do
-      jupyter kernelspec install ${PYENV_ROOT}/versions/${python_version}/share/jupyter/kernels/python* || (echo "Could not install Python ${python_version} kernel!" && exit 1)
+    for KERNELPATH in $(dirname $(ls ${PYENV_ROOT}/versions/*/share/jupyter/kernels/python*/kernel.json)); do
+      /usr/bin/jupyter kernelspec install $KERNELPATH  || die "Could not install Python ${python_version} kernel!";
     done
 
   # Install any missing R packages - approximately 1 hr
@@ -367,7 +373,7 @@ runcmd:
   - |
     sed -i "s|\"display_name\":.*\R.*|\"display_name\": \"R ${R_VERSION}\",|" /usr/local/lib/R/site-library/IRkernel/kernelspec/kernel.json
   - ln -s /usr/local/lib/R/site-library/IRkernel/kernelspec /usr/local/lib/R/site-library/IRkernel/R${R_VERSION}
-  - jupyter kernelspec install /usr/local/lib/R/site-library/IRkernel/R${R_VERSION} || (echo "Could not install R kernel!" && exit 1)
+  - jupyter kernelspec install /usr/local/lib/R/site-library/IRkernel/R${R_VERSION} || die "Could not install R kernel!";
 
   # Check for successful installations
   - echo ">=== $(date +%s) Checking environment configuration ===<"
@@ -383,7 +389,7 @@ runcmd:
   - echo "Setting PATH to '${PATH}'"
   - sed -i "s|^export PATH=.*|export PATH=${PATH}|" /etc/bash.bashrc
   # Run installation tests
-  - python3 /opt/build/check_installation.py || exit 1
+  - python3 /opt/build/check_installation.py || die "Installation check failed!";
 
   # Clean up any build artifacts
   - echo ">=== $(date +%s) Cleaning up the build environment ===<"
