:art: Restructure build process with better logging of build failures

diff --git a/.github/workflows/build_docs.yaml b/.github/workflows/build_docs.yaml
--- a/.github/workflows/build_docs.yaml
+++ b/.github/workflows/build_docs.yaml
@@ -34,33 +34,49 @@ jobs:
         run: |
           echo "BACKUPDIR=$(mktemp -d)" >> $GITHUB_ENV
           echo "OUTPUTDIR=$(mktemp -d)" >> $GITHUB_ENV
-      - name: Build latest documentation
+      - name: Save Sphinx config to BACKUPDIR
         shell: bash
         run: |
-          # Save config to BACKUPDIR then build
           ./docs/build/build_config_backup.sh -b -d ${{env.BACKUPDIR}}
-          ./docs/build/build_docs_instance.sh -p -d ${{env.OUTPUTDIR}} -n develop
-          latest_stable=$(git tag | grep -v beta | sort | tail -n 1)
-          sed "s|{{latest_stable}}|$latest_stable|g" docs/build/meta/index.html > ${{env.OUTPUTDIR}}/index.html
+      - name: Find latest stable release
+        shell: bash
+        run: |
+          LATEST_STABLE=$(git tag | grep -v beta | sort | tail -n 1)
+          echo "Setting default documentation version to $LATEST_STABLE"
+          sed "s|{{latest_stable}}|$LATEST_STABLE|g" docs/build/meta/index.html > ${{env.OUTPUTDIR}}/index.html
           touch ${{env.OUTPUTDIR}}/.nojekyll
-      - name: Build tagged documentation
+          echo "LATEST_STABLE=$LATEST_STABLE" >> $GITHUB_ENV
+      - name: Build documentation from development branch
+        shell: bash
+        run: |
+          ./docs/build/build_docs_instance.sh -p -d ${{env.OUTPUTDIR}} -n develop
+      - name: Build documentation from tagged releases
         shell: bash
         run: |
           git config --global advice.detachedHead false
           for tag in $(git tag); do
             echo -e "\n\n✨ Generating documention for ${tag} ✨"
             git checkout $tag
-            # Remove the software request form which contains invalid markdown in old releases
-            pwd
-            ls -alh
-            if [ ! -e "docs/build/conf.py" ]; then
-              find . -name "software-package-request-form.md" -exec rm {} \;
-            fi
-            # Reload Sphinx config to get a consistent HTML style then build
+            # Reload Sphinx config from BACKUPDIR to get a consistent HTML style
             ${{env.BACKUPDIR}}/build/build_config_backup.sh -l -d ${{env.BACKUPDIR}}
+            # Build HTML output
             ./docs/build/build_docs_instance.sh -d ${{env.OUTPUTDIR}} -n ${tag}
             echo "✨ Finished working on ${tag} ✨"
           done
+      - name: Check that all tags have built
+        shell: bash
+        run: |
+          FAILED=0
+          for tag in $(git tag); do
+            if [ -e "${{env.OUTPUTDIR}}/${tag}/index.html" ]; then
+              echo "✅ $tag documentation built successfully"
+            else
+              echo "❌ $tag documentation failed to build!"
+              FAILED=1
+            fi
+          done
+          ls -alh ${{env.OUTPUTDIR}}/*
+          if [ "$FAILED" = "1" ]; then exit 1; fi
       - name: Deploy documentation to GitHub Pages
         uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92  # This commit corresponds to tag (4.1.4)
         with:
